import { FileText } from 'lucide-react';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-3 pb-6 border-b border-gray-100 dark:border-gray-800 last:pb-0 last:border-0">
      <h2 className="text-base font-bold text-gray-900 dark:text-gray-100">{title}</h2>
      <div className="text-gray-600 dark:text-gray-400 leading-relaxed space-y-3 text-sm">{children}</div>
    </div>
  );
}

export default function TermsOfUsePage() {
  return (
    <div className="max-w-2xl mx-auto px-4 sm:px-6 py-10 space-y-8 animate-fade-in">
      <div>
        <div className="flex items-center gap-3 mb-3">
          <div className="w-10 h-10 bg-blue-50 dark:bg-blue-950/60 rounded-xl flex items-center justify-center">
            <FileText size={20} className="text-blue-600 dark:text-blue-400" />
          </div>
          <h1 className="page-title">Terms of Use</h1>
        </div>
        <p className="text-sm text-gray-400 dark:text-gray-500">Last updated: July 2026</p>
      </div>

      <div className="card p-6 sm:p-8 space-y-6">
        <Section title="1. Acceptance of Terms">
          <p>By using EverydayUtils, you agree to these Terms of Use. If you do not agree, please do not use the Service.</p>
        </Section>

        <Section title="2. Description of Service">
          <p>EverydayUtils provides free, browser-based utility tools that run entirely client-side.</p>
        </Section>

        <Section title="3. Permitted Use">
          <p>You may use the tools for personal or commercial purposes and use the generated outputs in your work.</p>
        </Section>

        <Section title="4. Prohibited Use">
          <p>You may not use the Service for illegal activities, attempt to reverse engineer the site, or abuse it with automated scripts.</p>
        </Section>

        <Section title="5. Age Requirement">
          <p>You must be at least 13 years old, or the age of digital consent in your jurisdiction, to use this Service.</p>
        </Section>

        <Section title="6. Disclaimer of Warranties">
          <p>The Service is provided “as is” without any warranties. We do not guarantee that the tools will be error-free or suitable for any particular purpose.</p>
        </Section>

        <Section title="7. Limitation of Liability">
          <p>To the maximum extent permitted by law, EverydayUtils shall not be liable for any damages arising from your use of the Service.</p>
        </Section>

        <Section title="8. Intellectual Property">
          <p>The EverydayUtils website and code are protected by copyright. Outputs generated by users belong to the user.</p>
        </Section>

        <Section title="9. Governing Law">
          <p>These Terms are governed by and construed in accordance with the laws of the Hong Kong Special Administrative Region.</p>
        </Section>

        <Section title="10. Changes to Terms">
          <p>We may update these Terms. Continued use after changes constitutes acceptance of the new terms.</p>
        </Section>
      </div>
    </div>
  );
}