import { FileText } from 'lucide-react';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="space-y-3 pb-6 border-b border-gray-100 dark:border-gray-800 last:pb-0 last:border-0">
      <h2 className="text-base font-bold text-gray-900 dark:text-gray-100">{title}</h2>
      <div className="text-gray-600 dark:text-gray-400 leading-relaxed space-y-3 text-sm">{children}</div>
    </div>
  );
}

export default function TermsOfUsePage() {
  return (
    <div className="max-w-2xl mx-auto px-4 sm:px-6 py-10 space-y-8 animate-fade-in">
      <div>
        <div className="flex items-center gap-3 mb-3">
          <div className="w-10 h-10 bg-blue-50 dark:bg-blue-950/60 rounded-xl flex items-center justify-center">
            <FileText size={20} className="text-blue-600 dark:text-blue-400" />
          </div>
          <h1 className="page-title">Terms of Use</h1>
        </div>
        <p className="text-sm text-gray-400 dark:text-gray-500">Last updated: June 2026</p>
      </div>

      <div className="card p-6 sm:p-8 space-y-6">
        <Section title="1. Acceptance of Terms">
          <p>By accessing and using EverydayUtils ("the Service"), you accept and agree to be bound by these Terms of Use. If you do not agree, please do not use the Service.</p>
        </Section>

        <Section title="2. Description of Service">
          <p>EverydayUtils provides a collection of browser-based utility tools free of charge. All tools operate entirely client-side within your web browser. The Service is provided "as is" without any warranties.</p>
        </Section>

        <Section title="3. Permitted Use">
          <p>You may use EverydayUtils for personal or commercial purposes. You may:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use any tool on the site freely</li>
            <li>Share links to any page or tool</li>
            <li>Use outputs generated by the tools in your personal or commercial work</li>
          </ul>
        </Section>

        <Section title="4. Prohibited Use">
          <p>You may not:</p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Use the Service for any illegal activity</li>
            <li>Attempt to reverse engineer or copy the site without permission</li>
            <li>Use automated means to abuse or overload the Service</li>
            <li>Misrepresent the origin or ownership of the tools</li>
          </ul>
        </Section>

        <Section title="5. Disclaimer of Warranties">
          <p>The Service is provided "as is" and "as available" without warranty of any kind. EverydayUtils makes no warranties, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.</p>
          <p>We do not guarantee that any tool will be accurate, error-free, or suitable for any specific purpose. Always verify outputs from automated tools, especially for critical applications like security (passwords) or professional work.</p>
        </Section>

        <Section title="6. Limitation of Liability">
          <p>To the maximum extent permitted by law, EverydayUtils shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of or inability to use the Service.</p>
        </Section>

        <Section title="7. Intellectual Property">
          <p>The EverydayUtils website, brand, and original code are protected by copyright. Tool outputs generated by users (passwords, QR codes, color palettes, etc.) belong entirely to the user who generated them.</p>
        </Section>

        <Section title="8. Changes to Terms">
          <p>We reserve the right to modify these Terms of Use at any time. Changes will be indicated by updating the "Last updated" date. Continued use of the Service after changes constitutes acceptance of the new terms.</p>
        </Section>

        <Section title="9. Governing Law">
          <p>These Terms of Use are governed by and construed in accordance with applicable law. Any disputes arising from use of the Service shall be handled in good faith.</p>
        </Section>
      </div>
    </div>
  );
}
